autoencoder:
  base_learning_rate: 2.0e-06
  target: models.autoencoder.VAutoEncoder
  params:
    learning_rate: 0.5
    encoder_config:
      target: modules.autoencoder.encoder.VEncoder
      params:
        base_channels: 128
        num_groups: 32
        z_scale_factor: 0.18215
    decoder_config:
      target: modules.autoencoder.decoder.VDecoder
      params:
        base_channels: 128
        num_groups: 32
        z_scale_factor: 0.18215
